DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS ordered_items CASCADE;

CREATE TABLE IF NOT EXISTS users (
	id BIGINT GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(255) NOT NULL,
	address VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	role VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
	);

CREATE TABLE IF NOT EXISTS orders (
	order_id BIGINT GENERATED ALWAYS AS IDENTITY,
	user_id BIGINT NOT NULL,
	order_date DATE NOT NULL,
	order_status VARCHAR(255) NOT NULL,
	order_title VARCHAR(255) NOT NULL,
	order_description VARCHAR(255) NOT NULL,
	order_sum_total NUMERIC NOT NULL,
	PRIMARY KEY(order_id),
	CONSTRAINT fk_user
		FOREIGN KEY(user_id)
			REFERENCES users(id)
			ON DELETE CASCADE
			ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS items (
	item_id BIGINT GENERATED ALWAYS AS IDENTITY,
	name VARCHAR(255) NOT NULL,
	price NUMERIC NOT NULL,
	PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS ordered_items (
	id BIGINT GENERATED ALWAYS AS IDENTITY,
	order_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    price NUMERIC NOT NULL,
	quantity INT NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT fk_order
		FOREIGN KEY(order_id)
			REFERENCES orders(order_id)
			ON DELETE CASCADE
			ON UPDATE CASCADE
);
